<?php
declare(strict_types=1);
$app = require dirname(__DIR__) . '/app/container.php';
$storePath = '/' . trim((string) ($app['config']['public_store_path'] ?? '/v1'), '/');
$storePath = $storePath === '/' ? '' : $storePath;
$assetPath = $storePath . '/assets';
$apiUrl = $storePath . '/api.php';
$storeUrl = $storePath === '' ? '/' : $storePath . '/';
$quoteAssetsVersion = (string) max(
    filemtime(__DIR__ . '/assets/quote.js') ?: 0,
    filemtime(__DIR__ . '/assets/quote-carousel.css') ?: 0
);
$escape = static fn (string $value): string => htmlspecialchars($value, ENT_QUOTES, 'UTF-8');
header("Content-Security-Policy: default-src 'self'; style-src 'self'; script-src 'self'; connect-src 'self'; img-src 'self' https: data:; base-uri 'self'; form-action 'self'");
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Cotizador para Emprendedores · Laboratorio Digital</title><link rel="icon" href="<?= $escape($assetPath) ?>/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="<?= $escape($assetPath) ?>/quote.css?v=<?= $quoteAssetsVersion ?>"><link rel="stylesheet" href="<?= $escape($assetPath) ?>/quote-table.css?v=<?= $quoteAssetsVersion ?>"><link rel="stylesheet" href="<?= $escape($assetPath) ?>/quote-carousel.css?v=<?= $quoteAssetsVersion ?>"></head>
<body><main class="quote-shell"><a class="quote-back" href="<?= $escape($storePath ?: '/') ?>">← Volver a Laboratorio Digital</a><header class="quote-hero"><span>✦ HERRAMIENTA ATELIER</span><h1>Tu idea, <em>bien cotizada.</em></h1><p>Calculá papel, tinta y una ganancia saludable para cada trabajo de tarjetería o papelería.</p></header>
<section class="quote-card"><div class="quote-step"><b>1</b><div><h2>Elegí tu papel</h2><p>Elegí entre los papeles disponibles en Laboratorio Digital.</p></div></div><button id="paper-picker" class="paper-picker" type="button" aria-expanded="false">Elegí el papel que más te guste <span>⌄</span></button><p id="paper-selected" class="paper-selected" hidden></p><div id="paper-picker-panel" class="paper-picker-panel" hidden><div id="paper-list" class="paper-list"><p>Cargando papeles…</p></div></div></section>
<section class="quote-guide"><strong>Medidas de referencia</strong><span>A4 · 21 × 29,7 cm</span><span>A3 · 29,7 × 42 cm</span><span>A3+ · 32,9 × 48,3 cm</span><span>A6 / 4R · 10 × 15 cm</span></section>
<section class="quote-card quote-project"><div class="quote-step"><b>2</b><div><h2>Contanos tu proyecto</h2><p>Usamos el tamaño real del papel elegido para aprovecharlo al máximo.</p></div></div><div class="quote-fields"><label>Cantidad de piezas<input id="project-quantity" type="number" min="1" value="200"></label><label>Ancho de cada pieza (cm)<input id="project-width" type="number" min="0.1" step="0.1" value="10"></label><label>Alto de cada pieza (cm)<input id="project-height" type="number" min="0.1" step="0.1" value="15"></label><label>Margen de corte (mm)<input id="cut-margin" type="number" min="0" step="0.5" value="0"></label></div><p class="quote-tip"><strong>¿Qué es el sangrado?</strong> Es el excedente que se deja alrededor del diseño para cortar sin bordes blancos. Si tu archivo lleva sangrado o necesitás espacio entre cortes, cargalo acá.</p></section>
<section class="quote-card"><div class="quote-step"><b>3</b><div><h2>Sumá la tinta</h2><p>Usamos el juego completo CMYK (4 tintas). El rendimiento se estima en hojas A4 de cobertura estándar.</p></div></div><div class="quote-fields ink-fields"><label>Línea de tinta<select id="ink-type"><option value="commercial">Comercial · juego CMYK 4 × 100 cc</option><option value="professional">Profesional · juego CMYK 4 × 100 cc</option><option value="eternity">Eternity · juego CMYK 4 × 100 cc</option></select></label><label>Cobertura estimada<select id="ink-coverage"><option value="0.5">Diseño suave · 50%</option><option value="1" selected>Color estándar · 100%</option><option value="1.5">Full color · 150%</option><option value="2">Foto intensa · 200%</option></select></label><label>Margen de ganancia (%)<input id="profit-margin" type="number" min="0" value="50"></label></div></section>
<section id="quote-result" class="quote-result" aria-live="polite"><p>Elegí un papel para ver tu cotización.</p></section>
<section id="related-products" class="related-products" aria-label="Productos Atelier"></section></main><script>window.quoteApp={apiUrl:<?= json_encode($apiUrl) ?>,storeUrl:<?= json_encode($storeUrl) ?>};</script><script src="<?= $escape($assetPath) ?>/quote.js?v=<?= $quoteAssetsVersion ?>"></script></body></html>
