<?php
declare(strict_types=1);
$app = require dirname(__DIR__) . '/app/container.php';
$storePath = '/' . trim((string) ($app['config']['public_store_path'] ?? '/v1'), '/');
$storePath = $storePath === '/' ? '' : $storePath;
$assetPath = $storePath . '/assets';
$apiUrl = $storePath . '/api.php';
$escape = static fn (string $value): string => htmlspecialchars($value, ENT_QUOTES, 'UTF-8');
header("Content-Security-Policy: default-src 'self'; style-src 'self'; script-src 'self'; connect-src 'self'; img-src 'self' https: data:; base-uri 'self'; form-action 'self'");
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Cotizador para Emprendedores · Laboratorio Digital</title><link rel="icon" href="<?= $escape($assetPath) ?>/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="<?= $escape($assetPath) ?>/quote.css"></head>
<body><main class="quote-shell"><a class="quote-back" href="<?= $escape($storePath ?: '/') ?>">← Volver a Laboratorio Digital</a><header class="quote-hero"><span>✦ HERRAMIENTA ATELIER</span><h1>Tu idea, <em>bien cotizada.</em></h1><p>Calculá papel, tinta y una ganancia saludable para cada trabajo de tarjetería o papelería.</p></header>
<section class="quote-card"><div class="quote-step"><b>1</b><div><h2>Elegí tu papel</h2><p>Buscá por nombre, variante o gramaje.</p></div></div><label class="quote-search">⌕ <input id="paper-search" type="search" placeholder="Ej.: A4 100 g"></label><div id="paper-list" class="paper-list"><p>Cargando papeles…</p></div></section>
<section class="quote-card quote-project"><div class="quote-step"><b>2</b><div><h2>Contanos tu proyecto</h2><p>Usamos el tamaño de la hoja elegida para aprovecharla al máximo.</p></div></div><div class="quote-fields"><label>Cantidad de piezas<input id="project-quantity" type="number" min="1" value="200"></label><label>Ancho de cada pieza (cm)<input id="project-width" type="number" min="0.1" step="0.1" value="10"></label><label>Alto de cada pieza (cm)<input id="project-height" type="number" min="0.1" step="0.1" value="15"></label><label>Margen de corte (mm)<input id="cut-margin" type="number" min="0" step="0.5" value="0"></label></div><p class="quote-tip">Tip: sumá el sangrado o espacio entre cortes como margen para obtener una estimación más segura.</p></section>
<section class="quote-card"><div class="quote-step"><b>3</b><div><h2>Sumá la tinta</h2><p>El rendimiento se estima en hojas A4 de cobertura estándar; podés cambiar la cobertura para tu diseño.</p></div></div><div class="quote-fields ink-fields"><label>Línea de tinta<select id="ink-type"><option value="commercial">Comercial</option><option value="professional">Profesional</option><option value="eternity">Eternity</option></select></label><label>Cobertura estimada<select id="ink-coverage"><option value="0.5">Diseño suave · 50%</option><option value="1" selected>Color estándar · 100%</option><option value="1.5">Full color · 150%</option><option value="2">Foto intensa · 200%</option></select></label><label>Margen de ganancia (%)<input id="profit-margin" type="number" min="0" value="50"></label></div></section>
<section id="quote-result" class="quote-result" aria-live="polite"><p>Elegí un papel para ver tu cotización.</p></section>
<section class="atelier"><h2>Para terminar tu proyecto ✿</h2><p>Pequeñas herramientas que hacen una gran diferencia.</p><div><span>✂ Guillotina o cutter</span><span>⌁ Regla metálica</span><span>◌ Base de corte</span><span>♡ Redondeadora de esquinas</span></div></section></main><script>window.quoteApp={apiUrl:<?= json_encode($apiUrl) ?>};</script><script src="<?= $escape($assetPath) ?>/quote.js"></script></body></html>
