<?php
declare(strict_types=1);

$app = require dirname(__DIR__) . '/app/container.php';
\LaboratorioDigital\Http::noCache();
$design = $app['settings']->design();
$storePath = '/' . trim((string) ($app['config']['public_store_path'] ?? '/v1'), '/');
$storePath = $storePath === '/' ? '' : $storePath;
$assetPath = $storePath . '/assets';
$assetVersion = substr(hash('sha256', (string) @file_get_contents(__DIR__ . '/assets/app.css') . (string) @file_get_contents(__DIR__ . '/assets/light.css')), 0, 12);
$brandAssetVersion = '20260826';
$storeUrl = $storePath === '' ? '/' : $storePath . '/';
$escape = static fn (string $value): string => htmlspecialchars($value, ENT_QUOTES, 'UTF-8');
?>
<!doctype html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Descargables · Laboratorio Digital</title>
    <link rel="icon" href="<?= $escape($assetPath) ?>/favicon.png?v=<?= $brandAssetVersion ?>" type="image/png">
    <link rel="stylesheet" href="<?= $escape($assetPath) ?>/app.css?v=<?= $escape($assetVersion) ?>">
    <link rel="stylesheet" href="<?= $escape($assetPath) ?>/light.css?v=<?= $escape($assetVersion) ?>">
</head>
<body class="downloads-page">
    <header class="store-header">
        <div class="header-leading"><a class="brand" href="<?= $escape($storeUrl) ?>"><img class="brand-logo" src="<?= $escape($design['logo_path']) ?>?v=<?= $brandAssetVersion ?>" alt="Laboratorio Digital"></a></div>
        <a class="downloads-back-header" href="<?= $escape($storeUrl) ?>">← Volver a la tienda</a>
    </header>
    <main class="downloads-shell">
        <a class="downloads-back" href="<?= $escape($storeUrl) ?>">← Volver a la tienda <small>ESC</small></a>
        <header class="downloads-intro"><p>RECURSOS GRATUITOS</p><h1>Descargables</h1><span>Elegí un diseño y descargalo directamente desde Laboratorio Digital.</span></header>
        <section class="downloads-grid" aria-label="Archivos descargables">
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/mochila-verde.jpg" alt="Mochila para colorear verde"><div><h2>Mochila para colorear · verde</h2><p>Una mochilita para colorear, ideal para llenar de golosinas y regalar.</p><a href="<?= $escape($assetPath) ?>/downloads/mochila-verde.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/mochila-rosa.jpg" alt="Mochila para colorear rosa"><div><h2>Mochila para colorear · rosa</h2><p>Una versión alternativa de la mochilita para imprimir, colorear y regalar.</p><a href="<?= $escape($assetPath) ?>/downloads/mochila-rosa.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/llaveros-san-valentin.jpg" alt="Llaveros para San Valentín"><div><h2>Llaveros para San Valentín</h2><p>Diseños de llaveros para crear un regalo especial.</p><a href="<?= $escape($assetPath) ?>/downloads/llaveros-san-valentin.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/cartas-a-santa.jpg" alt="Cartas a Santa"><div><h2>Cartas a Santa</h2><p>Cartas y sobres listos para imprimir y preparar los deseos de Navidad.</p><a href="<?= $escape($assetPath) ?>/downloads/cartas-a-santa.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/buzon-santa.jpg" alt="Buzón de Santa"><div><h2>Buzón de Santa</h2><p>Plantilla para armar un buzón navideño.</p><a href="<?= $escape($assetPath) ?>/downloads/buzon-santa.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/calendario-2026.jpg" alt="Calendario 2026"><div><h2>Calendario 2026</h2><p>Calendario listo para imprimir.</p><a href="<?= $escape($assetPath) ?>/downloads/calendario-2026.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/dia-amigo.jpg" alt="Día del amigo"><div><h2>Día del amigo</h2><p>Diseño para celebrar y regalar.</p><a href="<?= $escape($assetPath) ?>/downloads/dia-amigo.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/semana-dulzura.jpg" alt="Semana de la dulzura"><div><h2>Semana de la dulzura</h2><p>Diseño especial para dulces y regalos.</p><a href="<?= $escape($assetPath) ?>/downloads/semana-dulzura.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/animalitos-canvas.jpg" alt="Animalitos con canvas"><div><h2>Animalitos con canvas</h2><p>Figuras para imprimir, recortar y armar.</p><a href="<?= $escape($assetPath) ?>/downloads/animalitos-canvas.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/anotador-estudiante.jpg" alt="Anotador día del estudiante"><div><h2>Anotador día del estudiante</h2><p>Diseño de anotador para regalar.</p><a href="<?= $escape($assetPath) ?>/downloads/anotador-estudiante.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/bienvenida-reyes.jpg" alt="Bienvenida para los Reyes Magos"><div><h2>Bienvenida para los Reyes Magos</h2><p>Cartel de bienvenida para imprimir.</p><a href="<?= $escape($assetPath) ?>/downloads/bienvenida-reyes.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/bolsita-visor.jpg" alt="Bolsita con visor"><div><h2>Bolsita con visor</h2><p>Plantilla de bolsita para armar.</p><a href="<?= $escape($assetPath) ?>/downloads/bolsita-visor.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/bolsita-estampitas.jpg" alt="Bolsita para estampitas"><div><h2>Bolsita para estampitas</h2><p>Packaging para recuerdos y estampitas.</p><a href="<?= $escape($assetPath) ?>/downloads/bolsita-estampitas.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/cajita-bruma.jpg" alt="Cajita con Bruma Clara"><div><h2>Cajita con Bruma Clara</h2><p>Plantilla de caja para imprimir y armar.</p><a href="<?= $escape($assetPath) ?>/downloads/cajita-bruma.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/pulseras-egresados.jpg" alt="Pulseras de egresados"><div><h2>Pulseras de egresados</h2><p>Diseños para egresados, eventos y recuerdos personalizados.</p><a href="<?= $escape($assetPath) ?>/downloads/pulseras-egresados.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/guirnalda-halloween.jpg" alt="Guirnalda de Halloween"><div><h2>Guirnalda de Halloween</h2><p>Plantilla para decorar Halloween en tres simples pasos.</p><a href="<?= $escape($assetPath) ?>/downloads/guirnalda-halloween.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/regalo-mama.jpg" alt="Regalo para mamá"><div><h2>Regalo para mamá</h2><p>Un detalle creativo para preparar y regalar con mucho cariño.</p><a href="<?= $escape($assetPath) ?>/downloads/regalo-mama.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/laberinto-ninez.jpg" alt="Laberinto Día de la Niñez"><div><h2>Laberinto Día de la Niñez</h2><p>Actividad con versiones espacial y de unicornios para imprimir.</p><a href="<?= $escape($assetPath) ?>/downloads/laberinto-ninez.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/memotest-italiano.jpg" alt="Memotest italiano"><div><h2>Memotest italiano</h2><p>Juego de memoria para imprimir, recortar y disfrutar.</p><a href="<?= $escape($assetPath) ?>/downloads/memotest-italiano.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/dia-amigo-frogcreativo.jpg" alt="Día del amigo por Frogcreativo"><div><h2>Día del amigo · Frogcreativo</h2><p>Un imprimible original con mensajes lindos para sorprender.</p><a href="<?= $escape($assetPath) ?>/downloads/dia-amigo-frogcreativo.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/tarjeta-mariposa-primavera.jpg" alt="Tarjeta mariposa de primavera"><div><h2>Tarjeta mariposa de primavera</h2><p>Tarjeta mariposa para celebrar la llegada de la primavera.</p><a href="<?= $escape($assetPath) ?>/downloads/tarjeta-mariposa-primavera.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/mini-candy.jpg" alt="Mini-Candy"><div><h2>Mini-Candy</h2><p>Plantilla para armar un Mini-Candy y llenarlo de dulces.</p><a href="<?= $escape($assetPath) ?>/downloads/mini-candy.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/tatuajes-navidenos.jpg" alt="Tatuajes navideños"><div><h2>Tatuajes navideños</h2><p>Tatuajes navideños listos para imprimir y recortar.</p><a href="<?= $escape($assetPath) ?>/downloads/tatuajes-navidenos.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/plantilla-primavera.jpg" alt="Plantilla primaveral"><div><h2>Plantilla primaveral</h2><p>Plantilla primaveral para imprimir y armar.</p><a href="<?= $escape($assetPath) ?>/downloads/plantilla-primavera.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/adorno-cajita-navidad.jpg" alt="Adorno cajita de Navidad"><div><h2>Adorno cajita de Navidad</h2><p>Adorno navideño en forma de cajita para imprimir y armar.</p><a href="<?= $escape($assetPath) ?>/downloads/adorno-cajita-navidad.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/sobre-fotos-dia-padre.jpg" alt="Sobre para fotos Día del Padre"><div><h2>Sobre para fotos · Día del Padre</h2><p>Sobre para fotos, especial para el Día del Padre.</p><a href="<?= $escape($assetPath) ?>/downloads/sobre-fotos-dia-padre.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/buzon-navideno.png" alt="Buzón navideño"><div><h2>Buzón navideño</h2><p>Buzón navideño para armar, llenar de golosinas y decorar las fiestas.</p><a href="<?= $escape($assetPath) ?>/downloads/buzon-navideno.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/cajita-navidena.png" alt="Cajita navideña"><div><h2>Cajita navideña</h2><p>Cajita con forma de árbol de Navidad para imprimir, armar y regalar.</p><a href="<?= $escape($assetPath) ?>/downloads/cajita-navidena.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/cajita-san-valentin-frogcreativo.png" alt="Cajita para San Valentín por Frogcreativo"><div><h2>Cajita San Valentín · Frogcreativo</h2><p>Cajita para San Valentín creada por Frogcreativo.</p><a href="<?= $escape($assetPath) ?>/downloads/cajita-san-valentin-frogcreativo.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/cajitas-triangulares-navidenas.png" alt="Cajitas triangulares navideñas"><div><h2>Cajitas triangulares navideñas</h2><p>Cajitas triangulares para preparar obsequios navideños.</p><a href="<?= $escape($assetPath) ?>/downloads/cajitas-triangulares-navidenas.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/calendario-2025.png" alt="Calendario 2025"><div><h2>Calendario 2025</h2><p>Calendario 2025 listo para imprimir y armar.</p><a href="<?= $escape($assetPath) ?>/downloads/calendario-2025.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/carterita-tiendahiski.png" alt="Carterita por Tienda Hiski"><div><h2>Carterita · Tienda Hiski</h2><p>Carterita imprimible creada por Tienda Hiski.</p><a href="<?= $escape($assetPath) ?>/downloads/carterita-tiendahiski.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/casita-navidena-frogcreativo.png" alt="Casita navideña por Frogcreativo"><div><h2>Casita navideña · Frogcreativo</h2><p>Casita navideña para regalar o decorar, creada por Frogcreativo.</p><a href="<?= $escape($assetPath) ?>/downloads/casita-navidena-frogcreativo.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/centro-mesa-navideno.png" alt="Centro de mesa navideño"><div><h2>Centro de mesa navideño</h2><p>Centro de mesa navideño para armar y llenar de caramelos.</p><a href="<?= $escape($assetPath) ?>/downloads/centro-mesa-navideno.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/calendario-magnetico-2025.png" alt="Calendario magnético 2025"><div><h2>Calendario magnético 2025</h2><p>Calendario preparado para imprimir en papel fotográfico magnético.</p><a href="<?= $escape($assetPath) ?>/downloads/calendario-magnetico-2025.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/dia-madre-frogcreativo.png" alt="Regalo del Día de la Madre por Frogcreativo"><div><h2>Día de la Madre · Frogcreativo</h2><p>Cajita para regalar una planta en el Día de la Madre.</p><a href="<?= $escape($assetPath) ?>/downloads/dia-madre-frogcreativo.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/dulce-o-truco-cajita.png" alt="Cajita Dulce o truco"><div><h2>Dulce o truco</h2><p>Cajita golosinera de Halloween para imprimir y armar.</p><a href="<?= $escape($assetPath) ?>/downloads/dulce-o-truco-cajita.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/fotos-navidenas.png" alt="Fotos navideñas"><div><h2>Fotos navideñas</h2><p>Diseños navideños para imprimir fotos y preparar regalos o decoraciones.</p><a href="<?= $escape($assetPath) ?>/downloads/fotos-navidenas.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/halloween-olivias-paper.png" alt="Halloween por Olivia's Paper"><div><h2>Halloween · Olivia's Paper</h2><p>Archivo para preparar una sorpresa dulce de Halloween.</p><a href="<?= $escape($assetPath) ?>/downloads/halloween-olivias-paper.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/packaging-navideno.png" alt="Packaging navideño"><div><h2>Packaging navideño</h2><p>Packaging navideño para presentar adornos y regalos.</p><a href="<?= $escape($assetPath) ?>/downloads/packaging-navideno.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/recuerdos-verano.png" alt="Recuerdos de verano"><div><h2>Recuerdos de verano</h2><p>Set de polaroids para imprimir y conservar recuerdos del verano.</p><a href="<?= $escape($assetPath) ?>/downloads/recuerdos-verano.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/cajita-primavera-olivias-paper.png" alt="Cajita de primavera por Olivia's Paper"><div><h2>Cajita de primavera · Olivia's Paper</h2><p>Cajita especial para celebrar la primavera.</p><a href="<?= $escape($assetPath) ?>/downloads/cajita-primavera-olivias-paper.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/cajita-golosinera.png" alt="Cajita golosinera"><div><h2>Cajita golosinera</h2><p>Cajita para imprimir, armar y regalar.</p><a href="<?= $escape($assetPath) ?>/downloads/cajita-golosinera.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/regalo-dia-maestro.png" alt="Regalo para el Día del Maestro"><div><h2>Regalo para el Día del Maestro</h2><p>Imprimible para sorprender a quienes dejan huella enseñando.</p><a href="<?= $escape($assetPath) ?>/downloads/regalo-dia-maestro.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/juego-dia-nino-frogcreativo.png" alt="Juego del Día de la Niñez por Frogcreativo"><div><h2>Juego Día de la Niñez · Frogcreativo</h2><p>Juego imprimible para celebrar el Día de la Niñez.</p><a href="<?= $escape($assetPath) ?>/downloads/juego-dia-nino-frogcreativo.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/llavero-amistad-frogcreativo.png" alt="Llavero de la amistad por Frogcreativo"><div><h2>Llavero de la amistad · Frogcreativo</h2><p>Diseño de llavero para celebrar la amistad.</p><a href="<?= $escape($assetPath) ?>/downloads/llavero-amistad-frogcreativo.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/llavero-dia-padre-frogcreativo.png" alt="Llavero del Día del Padre por Frogcreativo"><div><h2>Llavero Día del Padre · Frogcreativo</h2><p>Diseño de llavero para regalar en el Día del Padre.</p><a href="<?= $escape($assetPath) ?>/downloads/llavero-dia-padre-frogcreativo.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/mochila-dia-estudiante.png" alt="Mochila del Día del Estudiante"><div><h2>Mochila Día del Estudiante</h2><p>Mochila imprimible para celebrar el Día del Estudiante.</p><a href="<?= $escape($assetPath) ?>/downloads/mochila-dia-estudiante.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/pelota-fotos-frogcreativo.png" alt="Pelota con fotos por Frogcreativo"><div><h2>Pelota con fotos · Frogcreativo</h2><p>Pelota personalizada con fotos para imprimir y armar.</p><a href="<?= $escape($assetPath) ?>/downloads/pelota-fotos-frogcreativo.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/patito-frogcreativo.png" alt="Plantilla de patito por Frogcreativo"><div><h2>Plantilla de patito · Frogcreativo</h2><p>Plantilla de patito para imprimir y armar.</p><a href="<?= $escape($assetPath) ?>/downloads/patito-frogcreativo.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/sobre-matelina-holofan.png" alt="Sobre con Matelina y Holofan"><div><h2>Sobre con Matelina y Holofan</h2><p>Sobre para invitaciones preparado para combinar ambos materiales.</p><a href="<?= $escape($assetPath) ?>/downloads/sobre-matelina-holofan.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/ruleta-semana-dulzura-frogcreativo.png" alt="Ruleta de la Semana de la Dulzura por Frogcreativo"><div><h2>Ruleta Semana de la Dulzura · Frogcreativo</h2><p>Ruleta imprimible para regalar durante la Semana de la Dulzura.</p><a href="<?= $escape($assetPath) ?>/downloads/ruleta-semana-dulzura-frogcreativo.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/sobre-coquette-suena-crea-scrap.png" alt="Sobre coquette por Sueña y Crea Scrap"><div><h2>Sobre coquette · Sueña y Crea Scrap</h2><p>Sobre imprimible con un estilo delicado y creativo.</p><a href="<?= $escape($assetPath) ?>/downloads/sobre-coquette-suena-crea-scrap.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/tableta-chocolate-mama.png" alt="Tableta de chocolate para mamá"><div><h2>Tableta de chocolate para mamá</h2><p>Envoltorio imprimible para preparar un regalo dulce.</p><a href="<?= $escape($assetPath) ?>/downloads/tableta-chocolate-mama.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/caja-sorpresa-amigos.png" alt="Caja sorpresa para amigos"><div><h2>Caja sorpresa para amigos</h2><p>Caja para imprimir, armar y regalar a tus amigos.</p><a href="<?= $escape($assetPath) ?>/downloads/caja-sorpresa-amigos.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/valijita-pintar-dia-ninez.png" alt="Valijita para pintar del Día de la Niñez"><div><h2>Valijita para pintar · Día de la Niñez</h2><p>Incluye diseños, versión editable y fanzine para imprimir.</p><a href="<?= $escape($assetPath) ?>/downloads/valijita-pintar-dia-ninez.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/anotador-frogcreativo.png" alt="Anotador por Frogcreativo"><div><h2>Anotador · Frogcreativo</h2><p>Anotador imprimible para preparar y regalar.</p><a href="<?= $escape($assetPath) ?>/downloads/anotador-frogcreativo.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/caja-nutella-frogcreativo.png" alt="Caja de Nutella por Frogcreativo"><div><h2>Caja de Nutella · Frogcreativo</h2><p>Caja imprimible para presentar un regalo con Nutella.</p><a href="<?= $escape($assetPath) ?>/downloads/caja-nutella-frogcreativo.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/cajita-halloween-frogcreativo.png" alt="Cajita de Halloween por Frogcreativo"><div><h2>Cajita de Halloween · Frogcreativo</h2><p>Incluye versiones preparadas para papel y Filmilo.</p><a href="<?= $escape($assetPath) ?>/downloads/cajita-halloween-frogcreativo.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/cajita-shaker-frogcreativo.png" alt="Cajita shaker por Frogcreativo"><div><h2>Cajita shaker · Frogcreativo</h2><p>Cajita shaker floral para imprimir y armar.</p><a href="<?= $escape($assetPath) ?>/downloads/cajita-shaker-frogcreativo.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/calendario-3d.png" alt="Calendario 3D"><div><h2>Calendario 3D</h2><p>Calendario tridimensional editable para imprimir y armar.</p><a href="<?= $escape($assetPath) ?>/downloads/calendario-3d.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/conejito-filmilo-acetato.png" alt="Conejito con Filmilo acetato"><div><h2>Conejito con Filmilo acetato</h2><p>Cono con forma de conejito para preparar y regalar.</p><a href="<?= $escape($assetPath) ?>/downloads/conejito-filmilo-acetato.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/cubo-navideno.png" alt="Cubo navideño"><div><h2>Cubo navideño</h2><p>Cubo para imprimir, armar y decorar en Navidad.</p><a href="<?= $escape($assetPath) ?>/downloads/cubo-navideno.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/dia-ninez-casa-armable.png" alt="Casa armable del Día de la Niñez"><div><h2>Casa armable · Día de la Niñez</h2><p>Casa para imprimir, armar y jugar.</p><a href="<?= $escape($assetPath) ?>/downloads/dia-ninez-casa-armable.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/cajitas-waffles.png" alt="Cajitas de waffles"><div><h2>Cajitas de waffles</h2><p>Cajitas con forma de waffles para imprimir y armar.</p><a href="<?= $escape($assetPath) ?>/downloads/cajitas-waffles.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/dulce-o-truco-ataud.png" alt="Ataúd Dulce o truco"><div><h2>Dulce o truco · Ataúd</h2><p>Plantilla de ataúd para preparar una sorpresa de Halloween.</p><a href="<?= $escape($assetPath) ?>/downloads/dulce-o-truco-ataud.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/horario-escolar-frogcreativo.png" alt="Horario escolar por Frogcreativo"><div><h2>Horario escolar · Frogcreativo</h2><p>Horario escolar imprimible para organizar cada semana.</p><a href="<?= $escape($assetPath) ?>/downloads/horario-escolar-frogcreativo.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/primavera-plantilla.png" alt="Plantilla primaveral"><div><h2>Plantilla primaveral</h2><p>Diseño para imprimir, recortar y celebrar la primavera.</p><a href="<?= $escape($assetPath) ?>/downloads/primavera-plantilla.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/caja-sorpresa-dia-maestro.png" alt="Caja sorpresa del Día del Maestro"><div><h2>Caja sorpresa · Día del Maestro</h2><p>Caja para preparar un regalo especial para quienes enseñan.</p><a href="<?= $escape($assetPath) ?>/downloads/caja-sorpresa-dia-maestro.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/caja-sorpresa-dia-madre.png" alt="Caja sorpresa del Día de la Madre"><div><h2>Caja sorpresa · Día de la Madre</h2><p>Caja para imprimir, armar y regalar a mamá.</p><a href="<?= $escape($assetPath) ?>/downloads/caja-sorpresa-dia-madre.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/cajita-semana-dulzura.png" alt="Cajita de la Semana de la Dulzura"><div><h2>Cajita Semana de la Dulzura</h2><p>Cajita imprimible para preparar un regalo dulce.</p><a href="<?= $escape($assetPath) ?>/downloads/cajita-semana-dulzura.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/comienzo-clases-escolar.png" alt="Set para el comienzo de clases"><div><h2>Comienzo de clases</h2><p>Set escolar imprimible para acompañar la vuelta a clases.</p><a href="<?= $escape($assetPath) ?>/downloads/comienzo-clases-escolar.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/cubo-luces.png" alt="Cubo con luces"><div><h2>Cubo con luces</h2><p>Plantilla de cubo para armar y decorar con luces.</p><a href="<?= $escape($assetPath) ?>/downloads/cubo-luces.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/halloween-clasico.png" alt="Halloween clásico"><div><h2>Halloween clásico</h2><p>Diseño para imprimir y preparar una sorpresa de Halloween.</p><a href="<?= $escape($assetPath) ?>/downloads/halloween-clasico.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/milk-box-astronauta.png" alt="Milk box astronauta"><div><h2>Milk box astronauta</h2><p>Cajita temática para imprimir y armar.</p><a href="<?= $escape($assetPath) ?>/downloads/milk-box-astronauta.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/set-navidad.png" alt="Set de Navidad"><div><h2>Set de Navidad</h2><p>Diseños navideños para imprimir, armar y decorar.</p><a href="<?= $escape($assetPath) ?>/downloads/set-navidad.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/sorpresa-pascuas-filmilo.png" alt="Sorpresa de Pascuas con Filmilo"><div><h2>Sorpresa de Pascuas con Filmilo</h2><p>Diseño preparado para realizar con Filmilo Cool White.</p><a href="<?= $escape($assetPath) ?>/downloads/sorpresa-pascuas-filmilo.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/cajitas-animalitos.png" alt="Cajitas de animalitos"><div><h2>Cajitas de animalitos</h2><p>Incluye diseños de conejo, gato y oso para imprimir y armar.</p><a href="<?= $escape($assetPath) ?>/downloads/cajitas-animalitos.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/candy-gamer.png" alt="Candy Gamer"><div><h2>Candy Gamer</h2><p>Kit imprimible para preparar una celebración temática.</p><a href="<?= $escape($assetPath) ?>/downloads/candy-gamer.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/dia-ninez-monstruos-numeros.png" alt="Monstruos y números del Día de la Niñez"><div><h2>Monstruos y números · Día de la Niñez</h2><p>Juego imprimible para recortar, armar y disfrutar.</p><a href="<?= $escape($assetPath) ?>/downloads/dia-ninez-monstruos-numeros.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/molino-primaveral.png" alt="Molino primaveral"><div><h2>Molino primaveral</h2><p>Molino para imprimir, recortar y armar.</p><a href="<?= $escape($assetPath) ?>/downloads/molino-primaveral.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/porta-joyas.png" alt="Porta joyas"><div><h2>Porta joyas</h2><p>Porta joyas imprimible para preparar y regalar.</p><a href="<?= $escape($assetPath) ?>/downloads/porta-joyas.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/estampa-dia-maestro.png" alt="Estampa del Día del Maestro"><div><h2>Estampa Día del Maestro</h2><p>Estampa imprimible para celebrar a quienes enseñan.</p><a href="<?= $escape($assetPath) ?>/downloads/estampa-dia-maestro.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/semana-dulzura-frogcreativo.png" alt="Semana de la Dulzura por Frogcreativo"><div><h2>Semana de la Dulzura · Frogcreativo</h2><p>Imprimible para preparar y regalar durante esa semana especial.</p><a href="<?= $escape($assetPath) ?>/downloads/semana-dulzura-frogcreativo.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/promesa-lealtad-bandera.png" alt="Promesa de Lealtad a la Bandera"><div><h2>Promesa de Lealtad a la Bandera</h2><p>Incluye cajita y diploma para imprimir y armar.</p><a href="<?= $escape($assetPath) ?>/downloads/promesa-lealtad-bandera.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
            <article class="download-card"><img src="<?= $escape($assetPath) ?>/downloads/cajita-escarapela-frogcreativo.png" alt="Cajita para escarapela por Frogcreativo"><div><h2>Cajita para escarapela · Frogcreativo</h2><p>Packaging imprimible para guardar y presentar una escarapela.</p><a href="<?= $escape($assetPath) ?>/downloads/cajita-escarapela-frogcreativo.pdf" download><span>↓</span> DESCARGAR PDF</a></div></article>
        </section>
    </main>
    <script>document.addEventListener('keydown', event => { if (event.key === 'Escape') window.location.href = <?= json_encode($storeUrl) ?>; });</script>
</body>
</html>
