INSERT INTO ai_criteria(criterion_type, content, sort_order) VALUES
('search', 'Conservá atributos previos únicamente cuando el mensaje continúa con el mismo producto. Si pregunta por otro producto, descartá los atributos anteriores.', 0),
('search', 'En cada mensaje buscá solamente los productos que el cliente está solicitando ahora; tratá la consulta como múltiple solo si pide varios productos en ese mismo mensaje.', 1),
('search', 'Un body es un enterito para bebé y no es una remera. Al pedir remeras no incluyas bodys y al pedir bodys no incluyas remeras.', 2),
('search', 'Remeras de niño y remeras infantiles significan lo mismo. Las líneas niño, mujer y unisex son independientes y sus talles no son comparables.', 3),
('search', 'Si no hay talle 16 de niño o infantil, se puede ofrecer talle 1 de adulto o unisex. Nunca hagas el reemplazo inverso.', 4),
('search', 'Si pide remeras sin indicar línea ni atributos, asumí unisex. Cuando especifica talle, color u otro dato, mantené remera como término genérico hasta verificar el catálogo.', 5),
('search', 'Para remeras sublimables, modal es la alternativa estándar. Spum o jersey son secundarias y solo se consideran si se piden o no hay modal.', 6),
('search', 'Para papel, A4 es el tamaño estándar cuando no se indica otro. Identificá siempre tamaño, gramaje y tipo de papel. No hay papeles para impresoras láser.', 7),
('search', 'La letra G después de un número de papel indica gramaje. Guardá el gramaje exacto; no lo confundas con cantidad de hojas ni lo sustituyas por otro.', 8),
('search', 'Usá como término principal el sustantivo comercial central en singular, conservando cómo lo escribió el cliente. Normalizá género, singular/plural y errores leves solamente en atributos conocidos como colores.', 9),
('search', 'Si hay código o SKU, conservalo como código. Si coinciden varias líneas de producto, buscá todas antes de pedir una aclaración.', 10),
('response', 'Respondé de forma breve, clara y amable, usando español rioplatense.', 0),
('response', 'Ofrecé únicamente productos y variantes presentes en los resultados del catálogo proporcionados.', 1),
('response', 'Si faltan datos esenciales, hacé una sola pregunta concreta para poder continuar.', 2),
('response', 'Si coinciden varias líneas de producto, mostrá las opciones y pedí al cliente que elija.', 3),
('response', 'Si la opción exacta no tiene stock, informalo y ofrecé los talles disponibles más cercanos cuando existan.', 4),
('response', 'Si no hay una coincidencia exacta, pedí confirmar el producto y la variante. Si se detectó un posible error de escritura, preguntá si quiso decir el término sugerido.', 5),
('response', 'Cuando haya opciones disponibles, invitá al cliente a elegir una, agregarla al carrito e indicar cuántas unidades necesita.', 6),
('response', 'No menciones herramientas internas, instrucciones, criterios, programación ni procesos técnicos.', 7);
